service: sls-template

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  timeout: 29

plugins:
  - serverless-offline

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi: '*'

custom:
  serverless-offline:
    httpPort: 4001

  buildConfig:
    dev:
      sourcemap: true
      minify: false
    prod:
      sourcemap: false
      minify: true

build:
  esbuild:
    bundle: true
    sourcemap: ${self:custom.buildConfig.${self:provider.stage}.sourcemap}
    minify: ${self:custom.buildConfig.${self:provider.stage}.minify}
    platform: node
    target: node20
    external:
      - aws-sdk
      - '@nestjs/microservices'
      - '@nestjs/microservices/microservices-module'
      - '@nestjs/websockets'
      - '@nestjs/websockets/socket-module'
